#!/bin/bash
set -euo pipefail

FEATURE_DIR="$(cd "$(dirname "$0")" && pwd)"

if [ "${ENABLEFIREWALL}" = "true" ]; then
    regions_array=$(echo "${REGIONS}" | tr ',' '\n' | jq -Rsc '[split("\n")[] | select(length > 0)]')
    services_array=$(echo "${SERVICES}" | tr ',' '\n' | jq -Rsc '[split("\n")[] | select(length > 0)]')

    jq -r --argjson regions "${regions_array}" --argjson services "${services_array}" --argjson fips "${FIPS}" '
        .partitions[] | select(.partition == "aws") |
        . as $partition |
        .services | to_entries[] | . as $service |
        select($services | length == 0 or ($services | contains([$service.key]))) |
        .value.endpoints | to_entries[] |
        .key as $region |
        (if .value.hostname then .value.hostname
         else "\($service.key).\($region).\($partition.dnsSuffix)"
         end) as $hostname |
        select($fips or ($hostname | test("fips"; "i") | not)) |
        select($regions | length == 0 or ($regions | contains([$region]))) |
        $hostname
    ' "${FEATURE_DIR}/botocore-endpoints.json" | sort -u \
        > /usr/local/etc/firewall-extra-fqdns.d/feature-aws-autogenerated-fqdns.txt
fi

install -m 0644 "${FEATURE_DIR}/firewall-fqdns.txt" /usr/local/etc/firewall-extra-fqdns.d/feature-aws-fqdns.txt

install -o "${USERNAME}" -g "${USERNAME}" -m 0644 "${FEATURE_DIR}/mise.toml" "/home/${USERNAME}/.config/mise/conf.d/110-aws.toml"

if [ "${USEGRANTED}" = "true" ]; then
    mkdir -p /home/${USERNAME}/.granted
    chown ${USERNAME}:${USERNAME} /home/${USERNAME}/.granted
    install -o "${USERNAME}" -g "${USERNAME}" -m 0644 "${FEATURE_DIR}/mise.granted.toml" "/home/${USERNAME}/.config/mise/conf.d/111-aws-granted.toml"
fi
